### ISSUE TITLE
Periodically check the available leap rpc in miner

### ISSUE THREAD

**Issue by taokayan** [eosnetworkfoundation/eos-evm-miner#31]
the current behavior:

miner will rotate the leap rpc endpoint only when get gas price fails. And this bebavior will not respect the priority of leap end points defined in the config list.

expected new behavior:

miner will periodically check each configured leap endpoint and take the 1st available one according to configuration order.
PR targeting for release/0.1

**Comment by iamphoumin852** [comment]
Confirmed by Kayan that all miner running v0.1.1
