### ISSUE TITLE
Use send_transaction2 for eos-evm-miner with proper arguments

### ISSUE THREAD

**Issue by stephenpdeos** [eosnetworkfoundation/eos-evm-miner#34]
Use send_transaction2 with an include in block option

**Comment by stephenpdeos** [comment]
Depends on #39

**Comment by yarkinwho** [comment]
As discussed in #45, we will use send_transaction2 but with arguments that make it work same as send_transaction.

Now we repurpose this issue to track calling send_transaction2 with proper arguments that enables the features such as retry and trace.

**Comment by yarkinwho** [comment]
After more discussion, the decision is we will enable retry if tests show no significant performance impact.

We will not check the trace for now and let the request fail upon failure. We will revisit this checking trace requirement when we actually locate some cases that cannot be properly handled in current design.
